recipe: default.v1
language: en

# Pipeline for processing user messages
pipeline:
- name: NLUCommandAdapter
  # Required for intent-based slot mappings (confirm_reply and confirm_sending)
- name: CompactLLMCommandGenerator
  llm:
    model_group_id: openai-gpt4o
  minimize_num_calls: true
  prompt_template: prompts/custom_prompt_template.jinja2

# Policies for dialogue management
policies:
- name: FlowPolicy    # Handle Rasa Pro flow definitions
- name: IntentlessPolicy    # Support conversations without explicit intents
- name: RulePolicy    # Handle simple rules

# Model group for LLM API access
model_groups:
- id: openai-gpt4o
  models:
  - provider: openai
    model: gpt-4o-2024-11-20
    request_timeout: 10
    max_tokens: 500
    temperature: 0.7
assistant_id: 20250324-164058-glum-rack