recipe: default.v1
language: en

# Pipeline for natural language understanding
pipeline:
  - name: LLMIntentClassifier
    llm:
      model_name: "gpt-4"
      api_key: ${OPENAI_API_KEY}
    prompt_prefix: |
      You are an AI assistant helping with email management.
      Analyze the user's query to identify their intent.
      The user might want to:
      - Check for new emails
      - Read email content
      - Reply to emails
      - Sort or label emails

# Policies for dialogue management
policies:
  - name: FlowPolicy
  - name: IntentlessPolicy
  - name: LLMPolicy
    llm:
      model_name: "gpt-4"
      api_key: ${OPENAI_API_KEY}
    max_tokens: 256