recipe: default.v1
language: en

# Pipeline for processing user messages
pipeline:
- name: NLUCommandAdapter
  # Required for intent-based slot mappings (confirm_reply and confirm_sending)
- name: CompactLLMCommandGenerator
  llm:
    model_name: "gpt-4o-2024-11-20"    # Use the latest recommended model
    api_key: '${OPENAI_API_KEY}'
      # No need to specify a prompt template as we'll use the default optimized one

# Policies for dialogue management
policies:
- name: FlowPolicy    # Handle Rasa Pro flow definitions
- name: IntentlessPolicy    # Support conversations without explicit intents
- name: RulePolicy    # Handle simple rules

# Model group for LLM API access in custom actions
model_groups:
- id: openai-gpt4o
  models:
  - provider: openai
    model: gpt-4o-2024-11-20
    request_timeout: 10
    max_tokens: 500
assistant_id: 20250324-164058-glum-rack